/*
* DESCRIPTION:
Preamble
In Microsoft FreeCell (shipped with early Windows versions), each deal is generated by PRNG seeded by the deal number (see pseudocode below). There are 32000 deals numbered from 1 to 32000. This guarantees every deal is unique, but they are portable across computers, so #1 on one machine is exactly the same on other machines.

Your task
Your task is to implement the function which accepts a deal number (1 <= n <= 32000) and returns an array/list/table (depending on programming language) of the cards corresponding to the given deal. See the dealing process below.
* */